/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.Sesion;
import Controlador.servicio.CuentaServicio;
import Controlador.servicio.RolServicio;
import javax.swing.JOptionPane;

/**
 *
 * @author Milton Riofrio, Sebastian Gomez
 */
public class FrmRegistro extends javax.swing.JDialog {

    /**
     * Creates new form FrmRegistro
     */
    private RolServicio rs = new RolServicio();
    private CuentaServicio cs = new CuentaServicio();
    /**
     * Es la primero que se ejecuta de la vista
     * @param parent
     * @param modal
     */    
    public FrmRegistro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rs.crearRoles();
    }
    /**
     * Verifica si el inicio de secion es correcto, si los datos ingresados corresponden a los establecidos, para asi pasar a la siguiente ventana
     */    
    private void inicioSesion() {
        String usurio = txtUsuario.getText();
        String clave = new String(txtClave.getPassword());
        Sesion.setCuenta(cs.inicioSesion(usurio, clave));
        if (Sesion.getCuenta() != null) {
            if (Sesion.getCuenta().getUsuario() != null) {
                Sesion.cargarDatos();
                JOptionPane.showMessageDialog(this, "BIENVENIDO: " + Sesion.getEmpleado().toString() + "\n " 
                        + "Ha iniciado como: " + Sesion.getRol().toString());
                new RegistroEnvios().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Cuenta no activa", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Usuario no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        jButtonIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setLayout(null);

        jLabel1.setText("R E G I S T R O");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(140, 10, 92, 16);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 370, 40);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("REGISTRO PERSONAL"));
        jPanel3.setLayout(null);

        jLabel2.setText("USUARIO/C.I:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 50, 78, 16);

        jLabel3.setText("CONTRASEÑA:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 90, 79, 16);
        jPanel3.add(txtUsuario);
        txtUsuario.setBounds(140, 50, 190, 22);
        jPanel3.add(txtClave);
        txtClave.setBounds(140, 90, 190, 22);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 60, 360, 140);

        jButtonIngresar.setText("INGRESAR");
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonIngresar);
        jButtonIngresar.setBounds(150, 220, 90, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Verfica si los campos se han escrito, y se procede a iniciar sesion
     * @param evt
     */
    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        // TODO add your handling code here:
        if (txtClave.getPassword().length == 0 || txtUsuario.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene todo los campos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            inicioSesion();
        }
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmRegistro dialog = new FrmRegistro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
